name: CSV daily updater

# Execute daily
on:
  schedule:
    - cron: 0 5 31 2 *
  watch:
    types: [started]
    if: github.actor == github.event.repository.owner.login

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    # Runs a set of commands using the runners shell
    - name: Update csvs
      run: |
        git config --global user.email "marianocrosetti1993@gmail.com"
        git config --global user.name "mariano22"
        python csv_generator.py
        git add csvs/*
        git commit -m "Update csvs automatically"
        git push origin HEAD:master
